apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gds

resources:
- namespace.yaml
- postgres-oltp-deployment.yaml
- database-migration-job.yaml
- backend-deployment.yaml
- frontend-deployment.yaml
- services.yaml
- ingress.yaml

configMapGenerator:
  - name: database-migrations
    namespace: gds
    files:
      - ../migrations/sql

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/name: gds
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
