apiVersion: v1
kind: Service
metadata:
  name: gds-backend
  namespace: gds
  labels:
    app: gds-backend
spec:
  selector:
    app: gds-backend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: gds-frontend
  namespace: gds
  labels:
    app: gds-frontend
spec:
  selector:
    app: gds-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
